name: security-trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:
    inputs:
      run-sast:
        description: Executar SAST
        type: boolean
        default: true
      sast-output-format:
        description: Formato de saída do SAST
        type: choice
        default: sarif
        options:
          - sarif
          - sarif-template
          - json
          - table
      sast-ignore-unfixed:
        description: Ignorar vulnerabilidades sem correção (SAST)
        type: boolean
        default: true
      sast-pr-report:
        description: Comentar resultado do SAST no PR
        type: boolean
        default: false
      run-sca:
        description: Executar SCA
        type: boolean
        default: true
      include-sbom:
        description: Gerar SBOM durante o SCA
        type: boolean
        default: true
      sca-sarif-format:
        description: Formato do SARIF (nativo ou template)
        type: choice
        default: native
        options:
          - native
          - template
      sca-ignore-unfixed:
        description: Ignorar vulnerabilidades sem correção (SCA)
        type: boolean
        default: true
      sca-pr-report:
        description: Comentar resultado do SCA no PR
        type: boolean
        default: true
      fail-on-severity:
        description: Severidades que falham o build
        type: choice
        default: CRITICAL,HIGH
        options:
          - CRITICAL
          - CRITICAL,HIGH
          - CRITICAL,HIGH,MEDIUM
          - CRITICAL,HIGH,MEDIUM,LOW

permissions:
  contents: write
  security-events: write
  actions: read

jobs:
  sast:
    name: SAST
    if: ${{ github.event_name != 'workflow_dispatch' || inputs['run-sast'] }}
    uses: ./.github/workflows/trivy-sast.yml
    with:
      scan-ref: .
      severity: ${{ (github.event_name == 'workflow_dispatch' && inputs['fail-on-severity']) || (github.event_name != 'workflow_dispatch' && 'CRITICAL,HIGH') }}
      vuln-type: library
      scanners: vuln,secret,misconfig
      ignore-unfixed: ${{ (github.event_name == 'workflow_dispatch' && inputs['sast-ignore-unfixed']) || (github.event_name != 'workflow_dispatch' && true) }}
      exit-on-vulnerability: true
      output-format: ${{ (github.event_name == 'workflow_dispatch' && inputs['sast-output-format']) || (github.event_name != 'workflow_dispatch' && 'sarif') }}
      upload-sarif: ${{ (github.event_name == 'workflow_dispatch' && (inputs['sast-output-format'] == 'sarif' || inputs['sast-output-format'] == 'sarif-template')) || (github.event_name != 'workflow_dispatch' && true) }}
      publish-summary: true
      pr-report: ${{ (github.event_name == 'workflow_dispatch' && inputs['sast-pr-report']) || (github.event_name != 'workflow_dispatch' && false) }}
      fail-on-severity: ${{ (github.event_name == 'workflow_dispatch' && inputs['fail-on-severity']) || (github.event_name != 'workflow_dispatch' && 'CRITICAL,HIGH') }}

  sca:
    name: SCA
    if: ${{ github.event_name != 'workflow_dispatch' || inputs['run-sca'] }}
    uses: ./.github/workflows/trivy-sca.yml
    with:
      scan-ref: .
      severity: ${{ (github.event_name == 'workflow_dispatch' && inputs['fail-on-severity']) || (github.event_name != 'workflow_dispatch' && 'CRITICAL,HIGH') }}
      vuln-type: os,library
      scanners: vuln,secret,misconfig,license
      ignore-unfixed: ${{ (github.event_name == 'workflow_dispatch' && inputs['sca-ignore-unfixed']) || (github.event_name != 'workflow_dispatch' && true) }}
      exit-on-vulnerability: true
      sarif-format: ${{ (github.event_name == 'workflow_dispatch' && inputs['sca-sarif-format']) || (github.event_name != 'workflow_dispatch' && 'native') }}
      include-sbom: ${{ (github.event_name == 'workflow_dispatch' && inputs['include-sbom']) || (github.event_name != 'workflow_dispatch' && true) }}
      upload-sarif: true
      publish-summary: true
      pr-report: ${{ (github.event_name == 'workflow_dispatch' && inputs['sca-pr-report']) || (github.event_name != 'workflow_dispatch' && true) }}
      fail-on-severity: ${{ (github.event_name == 'workflow_dispatch' && inputs['fail-on-severity']) || (github.event_name != 'workflow_dispatch' && 'CRITICAL,HIGH') }}
